require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'tigerbudStarter' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNAWSCognito', :path => '../node_modules/amazon-cognito-identity-js'

  target 'tigerbudStarterTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({'Flipper' => '0.111.0'})
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'tigerbudStarter-tvOS' do
  # Pods for tigerbudStarter-tvOS

  target 'tigerbudStarter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
